export const ADD_RECIPE_BOX = "ADD_RECIPE_BOX";
export const DELETE_RECIPE_BOX = "DELETE_RECIPE_BOX";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";